easy_admin:
    site_name: 'O Faq'
    entities:
      Utilisateurs:
          class: App\Entity\User
          list:
            fields: ['id', 'roles', 'email', 'firstname', 'lastname', 'question', 'answer' ]
      Questions:
          class: App\Entity\Question
      Tag:
          class: App\Entity\Tag
      Reponses:
          class: App\Entity\Answer

